export const mockSearchResponse = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/tjmBUrys7BkctrkontuoiUiEZ0D.jpg',
      genre_ids: [35, 10751, 10770],
      id: 12536,
      original_language: 'en',
      original_title: 'Home Alone 4',
      overview:
        "Kevin McCallister's parents have split up. Now living with his mom, he decides to spend Christmas with his dad at the mansion of his father's rich girlfriend, Natalie. Meanwhile robber Marv Merchants, one of the villains from the first two movies, partners up with a new criminal named Vera to hit Natalie's mansion.",
      popularity: 24.319,
      poster_path: '/qRktvMOO2QaCL7gvNyvZDoxPOZj.jpg',
      release_date: '2002-11-03',
      title: 'Home Alone 4',
      video: false,
      vote_average: 4.504,
      vote_count: 1220,
    },
    {
      adult: false,
      backdrop_path: '/oHsiqHajO9v8YTuonvcMCkxtpSq.jpg',
      genre_ids: [35, 10751],
      id: 9714,
      original_language: 'en',
      original_title: 'Home Alone 3',
      overview:
        '9-year-old Alex Pruitt is home alone with the chicken pox. Turns out, due to a mix-up among nefarious spies, Alex was given a toy car concealing a top-secret microchip. Now Alex must fend off the spies as they try to break into his house to get it back.',
      popularity: 29.859,
      poster_path: '/6uOadrCfle0n2LOOxHbgWEdnrm2.jpg',
      release_date: '1997-12-12',
      title: 'Home Alone 3',
      video: false,
      vote_average: 5.278,
      vote_count: 2924,
    },
    {
      adult: false,
      backdrop_path: '/8fnYJPoXxwAN4valDLgz2whMGTH.jpg',
      genre_ids: [35, 10751, 12],
      id: 772,
      original_language: 'en',
      original_title: 'Home Alone 2: Lost in New York',
      overview:
        "Instead of flying to Florida with his folks, Kevin ends up alone in New York, where he gets a hotel room with his dad's credit card—despite problems from a clerk and meddling bellboy. But when Kevin runs into his old nemeses, the Wet Bandits, he's determined to foil their plans to rob a toy store on Christmas Eve.",
      popularity: 62.849,
      poster_path: '/uuitWHpJwxD1wruFl2nZHIb4UGN.jpg',
      release_date: '1992-11-15',
      title: 'Home Alone 2: Lost in New York',
      video: false,
      vote_average: 6.744,
      vote_count: 9299,
    },
    {
      adult: false,
      backdrop_path: '/en9bAOhdPXZJfx2xTf1WL5d1T5v.jpg',
      genre_ids: [35, 10751],
      id: 771,
      original_language: 'en',
      original_title: 'Home Alone',
      overview:
        "Eight-year-old Kevin McCallister makes the most of the situation after his family unwittingly leaves him behind when they go on Christmas vacation. But when a pair of bungling burglars set their sights on Kevin's house, the plucky kid stands ready to defend his territory. By planting booby traps galore, adorably mischievous Kevin stands his ground as his frantic mother attempts to race home before Christmas Day.",
      popularity: 3.126,
      poster_path: '/onTSipZ8R3bliBdKfPtsDuHTdlL.jpg',
      release_date: '1990-11-16',
      title: 'Home Alone',
      video: false,
      vote_average: 7.434,
      vote_count: 10876,
    },
    {
      adult: false,
      backdrop_path: '/a8tH0jl37366bLVyPB08dncgqqd.jpg',
      genre_ids: [35, 80, 10751],
      id: 654974,
      original_language: 'en',
      original_title: 'Home Sweet Home Alone',
      overview:
        'After being left at home by himself for the holidays, 10-year-old Max Mercer must work to defend his home from a married couple who tries to steal back a valuable heirloom.',
      popularity: 22.555,
      poster_path: '/fP3VvqUjEBjawxZHL4sYCq2ZdJD.jpg',
      release_date: '2021-11-12',
      title: 'Home Sweet Home Alone',
      video: false,
      vote_average: 5.0,
      vote_count: 596,
    },
    {
      adult: false,
      backdrop_path: '/4ydw24y7Wd0UJZOrd2FuRFqkfs.jpg',
      genre_ids: [35, 10751, 10770],
      id: 134375,
      original_language: 'en',
      original_title: 'Home Alone: The Holiday Heist',
      overview:
        '10-year-old Finn is terrified to learn his family is relocating from sunny California to Maine in the scariest house he has ever seen! Convinced that his new house is haunted, Finn sets up a series of elaborate traps to catch the “ghost” in action. Left home alone with his sister while their parents are stranded across town, Finn’s traps catch a new target – a group of thieves who have targeted Finn’s house.',
      popularity: 21.473,
      poster_path: '/6JPrRC0JPM06y17pUXD6w1xMvKi.jpg',
      release_date: '2012-12-03',
      title: 'Home Alone: The Holiday Heist',
      video: false,
      vote_average: 5.227,
      vote_count: 418,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 831993,
      original_language: 'en',
      original_title: 'Home Alone',
      overview: 'The atmosphere of parental distance',
      popularity: 1.316,
      poster_path: '/iTmJSG2pXArGXBP1LSDysWfGKzJ.jpg',
      release_date: '2013-01-01',
      title: 'Home Alone',
      video: false,
      vote_average: 5.1,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35, 27, 53],
      id: 1099636,
      original_language: 'pt',
      original_title: 'Home Alone',
      overview: '',
      popularity: 0.848,
      poster_path: '/wSIRHCnsnJEMLtYlmNb1q3OpPmI.jpg',
      release_date: '2023-03-13',
      title: 'Home Alone',
      video: true,
      vote_average: 5.0,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 1174314,
      original_language: 'es',
      original_title: 'Home Alone',
      overview: '',
      popularity: 1.639,
      poster_path: '/lAYUjJUN032qJ2xWQh0RAAd9zaF.jpg',
      release_date: '2018-07-09',
      title: 'Home Alone',
      video: false,
      vote_average: 8.0,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 1266070,
      original_language: 'ru',
      original_title: 'Не одна дома',
      overview: 'No description',
      popularity: 1.011,
      poster_path: '/mdo9mpX3u3BUPhrqs4uPooCg06t.jpg',
      release_date: '2024-07-18',
      title: 'Not Home Alone',
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/zFpW03mckR3p9JHRdVdkQVwuOUv.jpg',
      genre_ids: [18, 27],
      id: 889850,
      original_language: 'xx',
      original_title: 'Alene hjemme',
      overview: 'Bad dreams may come true...',
      popularity: 2.326,
      poster_path: '/3KklPhfWbyGCPtwObbOqVexEMyB.jpg',
      release_date: '1969-01-01',
      title: 'Home Alone',
      video: false,
      vote_average: 6.2,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: '/6xFIyGQvWeRVfmsMhg4iRMvtUsF.jpg',
      genre_ids: [35, 10751],
      id: 1224743,
      original_language: 'ru',
      original_title: 'Одна дома',
      overview:
        "Desperate to make the world more beautiful in a legitimate way, a young wayward engineer Artyom decided to rob several luxury apartments with the help of his invention. But in the first of them, he meets a cunning girl, Stefania, who demands to take her as an accomplice in order to buy a gift for her mother. They have only one New Year's Eve to pull off the case, and a lot of unforeseen circumstances.",
      popularity: 0.868,
      poster_path: '/4p543d34ULUZM4RQh6ZhvnWEZUw.jpg',
      release_date: '2023-12-07',
      title: 'Home Alone',
      video: true,
      vote_average: 10.0,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: '/3YJC8VLyqCP5Ynck53lP2hPOkBO.jpg',
      genre_ids: [10751, 35],
      id: 103844,
      original_language: 'da',
      original_title: 'Min søsters børn alene hjemme',
      overview: '',
      popularity: 2.857,
      poster_path: '/aa4VXdQIdRmJehnb2cxtNhVyBgC.jpg',
      release_date: '2012-02-02',
      title: "My Sister's Kids Home Alone",
      video: false,
      vote_average: 6.1,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: '/5mUTmmBFbsXlJE66XOumJSzYK7M.jpg',
      genre_ids: [27, 10749],
      id: 252171,
      original_language: 'en',
      original_title: 'A Girl Walks Home Alone at Night',
      overview:
        'In the Iranian ghost-town Bad City, a place that reeks of death and loneliness, the townspeople are unaware they are being stalked by a lonesome vampire.',
      popularity: 17.343,
      poster_path: '/cd2rCE1nun7CESjBI8PGNEof1tb.jpg',
      release_date: '2014-11-21',
      title: 'A Girl Walks Home Alone at Night',
      video: false,
      vote_average: 6.839,
      vote_count: 821,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 27, 53],
      id: 1252287,
      original_language: 'en',
      original_title: 'Home Alone',
      overview:
        'After being left home alone in a new house, Josian soon realizes that this new home might be more sinister than he thought.',
      popularity: 0.197,
      poster_path: '/9aoVG3nVTUMm14uU6HmDhCuhBDu.jpg',
      release_date: '2023-10-31',
      title: 'Home Alone',
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16],
      id: 454533,
      original_language: 'ja',
      original_title: 'Rusuban',
      overview:
        "It's the first time for the Cat to be all by itself at home. This Cat does not have a name yet and nobody knows whether it is female or male. And it has two faces, one is very sensitive and the other is rather naughty.",
      popularity: 0.244,
      poster_path: '/rDJHsdm5nN29O3BtGXZEaJrx5XN.jpg',
      release_date: '1996-01-01',
      title: 'Home Alone',
      video: false,
      vote_average: 4.3,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 18, 14, 27, 16],
      id: 761953,
      original_language: 'ja',
      original_title: 'こまねこのおるすばん',
      overview:
        'A fine day. Ojii leaves Koma alone at home. While Ojii is worried, Koma is a little excited, wondering if Ojii will be happy if she behaves nicely. In time, it begins to rain and thunder. And finally the light goes out. Koma, scared, shivers and something is behind her...! Can Koma go through this situation?',
      popularity: 0.117,
      poster_path: '/w4OJb7PPVoCxKc7qWp6kZfJjW02.jpg',
      release_date: '2013-01-01',
      title: 'Komaneko, Home Alone',
      video: false,
      vote_average: 7.3,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16],
      id: 959202,
      original_language: 'ru',
      original_title: 'Одна дома',
      overview: 'A short story about how the creative process takes place.',
      popularity: 0.141,
      poster_path: null,
      release_date: '2022-04-05',
      title: 'Alone at Home',
      video: false,
      vote_average: 3.7,
      vote_count: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16],
      id: 319125,
      original_language: 'ja',
      original_title: 'Nezumi no rusuban',
      overview:
        'This anime shows a mission commanded by the Lord of the Rats to bring food, but a cat is watching the mice, so the Lord of the Rats orders them to kill the Cat so that the mission is successful.',
      popularity: 0.286,
      poster_path: null,
      release_date: '1931-01-18',
      title: 'Home Alone Mice',
      video: false,
      vote_average: 5.4,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [10751, 35],
      id: 1066229,
      original_language: 'pl',
      original_title: 'Kevin sam w domu wedlug Dudzika i Jasia',
      overview:
        'A brand new look into the story of Kevin McCallister by the polish geniuses Dominik Dudzik and Jas Dmoch.',
      popularity: 0.254,
      poster_path: '/62hqIafAzwCFzjyGSIEwyKPAv7Z.jpg',
      release_date: '2022-12-16',
      title: "Dudzik \u0026 Jasiu's Home Alone",
      video: false,
      vote_average: 7.6,
      vote_count: 6,
    },
  ],
  total_pages: 3,
  total_results: 48,
};
